# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Minecraft Server installation tasks
  when: minecraft_enabled | bool
  tags:
    - setup-all
    - setup-minecraft
    - install-all
    - install-minecraft
  block:
    - name: Validate Minecraft Server configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Minecraft Server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Minecraft Server uninstallation tasks
  when: not minecraft_enabled | bool
  tags:
    - setup-all
    - setup-minecraft
  block:
    - name: Uninstall Minecraft Server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
